// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Data from "../Data.bs.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import Table from "@mui/material/Table";
import * as JsxPPXReactSupportU from "rescript/lib/es6/jsxPPXReactSupportU.js";
import Avatar from "@mui/material/Avatar";
import TableRow from "@mui/material/TableRow";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableHead from "@mui/material/TableHead";
import TableContainer from "@mui/material/TableContainer";

function MainTable(props) {
  var list = Data.nameList(undefined);
  return React.createElement("div", {
              className: "bg-red-400 flex border-2 rounded h-max border-red-400"
            }, React.createElement(TableContainer, {
                  children: React.createElement(Table, {
                        children: null
                      }, React.createElement(TableHead, {
                            children: React.createElement(TableRow, {
                                  children: null
                                }, React.createElement(TableCell, {
                                      children: "Dog"
                                    }), React.createElement(TableCell, {
                                      children: "Owner"
                                    }), React.createElement(TableCell, {
                                      children: "Schedule"
                                    }))
                          }), React.createElement(TableBody, {
                            children: Belt_Array.mapWithIndex(list, (function (index, item) {
                                    return JsxPPXReactSupportU.createElementVariadicWithKey(item.dog, TableRow, {
                                                children: null
                                              }, [
                                                React.createElement(TableCell, {
                                                      children: Caml_option.some(React.createElement(React.Fragment, {
                                                                children: null
                                                              }, React.createElement(Avatar, {
                                                                    alt: "Dog Photo",
                                                                    src: Caml_array.get(Data.dogImages, index).default,
                                                                    sx: {
                                                                      width: 56,
                                                                      height: 56
                                                                    }
                                                                  }), React.createElement("p", {
                                                                    className: " font-bold text-center font-serif"
                                                                  }, item.dog)))
                                                    }),
                                                React.createElement(TableCell, {
                                                      children: Caml_option.some(item.owner)
                                                    }),
                                                React.createElement(TableCell, {
                                                      children: Caml_option.some(item.schedule)
                                                    })
                                              ]);
                                  }))
                          }))
                }));
}

var make = MainTable;

export {
  make ,
}
/* Data Not a pure module */
