// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dayjs from "dayjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Faker from "@faker-js/faker";
import * as Dog1Jpg from "./assets/dog1.jpg";
import * as Dog2Jpg from "./assets/dog2.jpg";
import * as Dog3Jpg from "./assets/dog3.jpg";
import * as Dog4Jpg from "./assets/dog4.jpg";
import * as Dog5Jpg from "./assets/dog5.jpg";

var dog1 = Dog1Jpg;

var dog2 = Dog2Jpg;

var dog3 = Dog3Jpg;

var dog4 = Dog4Jpg;

var dog5 = Dog5Jpg;

var dogImages = [
  dog1,
  dog2,
  dog3,
  dog4,
  dog5
];

var dogsName = [
  "Rex",
  "Alfred",
  "Clifford",
  "Betsy",
  "Minnie"
];

function generateData() {
  var newData = Faker.faker.date.recent(undefined);
  return Dayjs(newData).format("dddd HH:mm");
}

function nameList() {
  return Belt_Array.map(dogsName, (function (dog) {
                return {
                        dog: dog,
                        owner: Faker.faker.person.fullName(undefined),
                        schedule: generateData(undefined)
                      };
              }));
}

export {
  dog1 ,
  dog2 ,
  dog3 ,
  dog4 ,
  dog5 ,
  dogImages ,
  dogsName ,
  generateData ,
  nameList ,
}
/* dog1 Not a pure module */
