// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainTable from "./components/MainTable.bs.js";

function index() {
  return React.createElement("div", {
              className: "flex w-screen h-screen justify-center items-center",
              style: {
                backgroundImage: "url(\"src/assets/background.png\")"
              }
            }, React.createElement("div", {
                  className: "flex bg-pink-200 border-2 p-8 border-pink-200 rounded flex-row "
                }, React.createElement("div", {
                      className: "flex flex-row"
                    }, React.createElement("div", {
                          className: "absolute  h-16 w-12 "
                        }, React.createElement("img", {
                              src: "src/assets/paw.png"
                            })), React.createElement("div", {
                          className: "space-y-6 text-center"
                        }, React.createElement("p", {
                              className: "text-4xl font-sans font-thin"
                            }, "Pet Schedules"), React.createElement("p", {
                              className: "text-medium text-gray-600 font-bold"
                            }, "Check the week's appointments"), React.createElement(MainTable.make, {})))));
}

export {
  index ,
}
/* react Not a pure module */
